keys:
  - &primary age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
  - &eclipse age1ggzgwplg0dzgyrfj58fmmk0tsaa0827f4adrujd07z5t5evf8peqdd84yt
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *eclipse
