keys:
  - &kinzoku_gpg EA514A4E0C8A34AFDB496181582B3B3E531B9211
  - &kinzoku_age age17qhu5jrzachdvprxtw4d06f6gp3hrag5u3705qvrj68dcza0ps4q03a53z
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *kinzoku_gpg
        age:
          - *kinzoku_age
