gui:
  nerdFontsVersion: "3"

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "<c-g>"
    command: "git commit -S -m"
    description: "commit and sign"
    context: "files"
    loadingText: "loading commit"
